// Generated by CoffeeScript 1.11.1
(function() {
  var chalk, currentPrice, parse, parser, prevVal, print, sleep, util;

  parser = require('osmosis');

  sleep = require('sleep');

  util = require('util');

  chalk = require('chalk');

  currentPrice = 0;

  prevVal = 0;

  console.log("Starting");

  parse = function() {
    return parser.get("http://www.coindesk.com/price/").find(".bpi-value.bpiUSD").set("value").data(function(result) {
      prevVal = currentPrice;
      return currentPrice = result.value;
    }).done(print);
  };

  print = function() {
    var text;
    text = chalk.red("Current value = " + currentPrice);
    if (currentPrice > prevVal) {
      text = chalk.blue("Current value = " + currentPrice);
    }
    return console.log(text);
  };

  setInterval((function() {
    return parse();
  }), 1000);

}).call(this);
